### ISSUE TITLE
[Mod Compatability] [1.15.2] Silent Gear Crimson Iron

### ISSUE THREAD

**Issue by Dragnier** [Roziiii/MoreMekanismOres#8]
It would be nice to have 2-5x processing capability for Silent Gear Crimson Iron added.

Edited for typo.

**Comment by rpop0** [comment]
I'll get onto it.
It already has 2x processing?

**Comment by Dragnier** [comment]
Oh, no. I must have hit 3 instead of 2. Sorry.

**Comment by rpop0** [comment]
Creating this, might take a while since I'm changing the way the mod will handle textures. (Max 2-3 days)

**Comment by rpop0** [comment]
Implemented.
